site_name: chip-seq tutorials
pages:
- Introduction: 'index.md'
- command line, basics: 'cli.md'
- Setup: 'install.md'
- sequence QC: 'fastqc.md'
- Mapping: 'mapping.md'
- Peak calling: 'peak.md'
- Contact: 'contact.md'
theme: readthedocs
