site_name: ChIP-seq tutorials
nav:
- Home: index.md
- "Command line, basics": cli.md
- Setup snakemake: snakemake.md
- Workflow ChIP-seq: chip-seq.md
- Workflow ATAC-seq: atac-seq.md
- Contact: contact.md
repo_url: https://github.com/ginolhac/chip-seq/
site_description: "ChIP-seq tutorial, University of Luxembourg, Department Life Sciences and Medecine"
theme: material
